### ISSUE TITLE
Use neume names instead of font's chars

### ISSUE THREAD

**Issue by anaskaejdar** [t-bullock/kassia#4]
This will make Kassia BNML files much more human-readable and human-writable, and will also provide the amount of abstraction necessary to be able to incorporate other people's fonts, which aren't structured the same way that Kassia's own fonts are.

##### PHASE 0: Starting point
- [x] Finalize KA New Stathis so we have a stable starting point
   - [x] <s>Consider using "Byzantine Musical Symbols" Unicode block</s>

##### PHASE 1: Implement the shorthand
- [x] Create abstractneume class
- [x] Replace the chars in neume_dict.py with the shorthand neume names
- [x] Translation layer to convert shorthand abstract neumes into font's chars
   - [x] Read a font's fontconfig.yaml file for char assignments
   - [x] For every neume, replace it with its char counterpart and rebuild the neumes_list

##### PHASE 2: KA New Stathis-based char shorthand
- [ ] Translation layer to convert KA New Stathis chars to shorthand abstract neumes

##### PHASE 3: Proper syntax
- [ ] Translation layer to convert shorthand abstract neumes into proper abstract neumes
   - [ ] For everything in the shorthand form, translate to proper
   - [ ] For everything in proper, translate to proper+positioning info
- [ ] Translation layer from proper abstract to concrete (font chars)
   - [ ] Read fontconfig.yaml for char assignments
   - [ ] For every neume combination, substitute it with the chars specified in fontconfig (if the given combination is defined therein)
   - [ ] For every neume, replace it with the chars specified in fontconfig
   - [ ] Create a stacking engine to spatially-align combinations that weren't defined in fontconfig

**Comment by anaskaejdar** [comment]
Is phase 2 necessary if we're breaking backwards compatibility anyway?

**Comment by ilizol** [comment]
> Is phase 2 necessary if we're breaking backwards compatibility anyway?

This will be helpful only for someone, I suppose @t-bullock, who has written many scores with the old format.

**Comment by anaskaejdar** [comment]
We're already going to break compatibility with existing scores once we implement issue #2 .

**Comment by t-bullock** [comment]
I don't think it's necessary, as long as we keep development in a separate branch for a while. I could always write a little script to convert old scores.
